---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: submit-queue
spec:
  storageClassName: submit-queue
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/sitecore/submitqueue"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: submit-queue
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: submit-queue