apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../deploy
- ../horizon

images:
- name: sitecore-xp1-cm
  newName: sahu123/sitecore-horizon-integration-xp1-cm
  newTag: latest

patchesStrategicMerge:
- patch-id.yaml
- patch-cm.yaml