apiVersion: v1
kind: Service
metadata:
  name: cortexprocessing
spec:
  selector:
    app: cortexprocessing
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortexprocessing
  labels:
    app: cortexprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortexprocessing
  template:
    metadata:
      labels:
        app: cortexprocessing
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-xp1-cortexprocessing
        image: sitecore-xp1-cortexprocessing
        ports:
        - containerPort: 80
        env:
        - name: Database_Server
          valueFrom:
            secretKeyRef:
              name: sitecore-databaseservername
              key: sitecore-databaseservername
        - name: Processing_Engine_Tasks_Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-processing-engine-tasks-database-username
              key: sitecore-processing-engine-tasks-database-username
        - name: Processing_Engine_Tasks_Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-processing-engine-tasks-database-password
              key: sitecore-processing-engine-tasks-database-password
        - name: Processing_Engine_Storage_Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-processing-engine-storage-database-username
              key: sitecore-processing-engine-storage-database-username
        - name: Processing_Engine_Storage_Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-processing-engine-storage-database-password
              key: sitecore-processing-engine-storage-database-password
        - name: Sitecore_License
          valueFrom:
            secretKeyRef:
              name: sitecore-license
              key: sitecore-license
        - name: Sitecore_ConnectionStrings_Processing.Engine.Storage
          value: Data Source=$(Database_Server);Initial Catalog=Sitecore.Processing.Engine.Storage;User ID=$(Processing_Engine_Storage_Database_Username);Password=$(Processing_Engine_Storage_Database_Password);
        - name: Sitecore_ConnectionStrings_Processing.Engine.Tasks
          value: Data Source=$(Database_Server);Initial Catalog=Sitecore.Processing.Engine.Tasks;User ID=$(Processing_Engine_Tasks_Database_Username);Password=$(Processing_Engine_Tasks_Database_Password);
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Liveness
          timeoutSeconds: 300
          periodSeconds: 30
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthz/ready
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Startup
          timeoutSeconds: 300
          periodSeconds: 30
          failureThreshold: 10
        volumeMounts:
        - mountPath: C:\inetpub\wwwroot\App_Data\logs
          name: logs
          subPath: cortexprocessing
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs
      imagePullSecrets:
      - name: sitecore-docker-registry