apiVersion: v1
kind: Service
metadata:
  name: xdbcollection
spec:
  selector:
    app: xdbcollection
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xdbcollection
  labels:
    app: xdbcollection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xdbcollection
  template:
    metadata:
      labels:
        app: xdbcollection
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-xp1-xdbcollection
        image: sitecore-xp1-xdbcollection
        ports:
        - containerPort: 80
        env:
        - name: Database_Server
          valueFrom:
            secretKeyRef:
              name: sitecore-databaseservername
              key: sitecore-databaseservername
        - name: Messaging_Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-messaging-database-username
              key: sitecore-messaging-database-username
        - name: Messaging_Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-messaging-database-password
              key: sitecore-messaging-database-password
        - name: Marketing_Automation_Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-marketing-automation-database-username
              key: sitecore-marketing-automation-database-username
        - name: Marketing_Automation_Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-marketing-automation-database-password
              key: sitecore-marketing-automation-database-password
        - name: Collection_ShardMapManager_Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-collection-shardmapmanager-database-username
              key: sitecore-collection-shardmapmanager-database-username
        - name: Collection_ShardMapManager_Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-collection-shardmapmanager-database-password
              key: sitecore-collection-shardmapmanager-database-password
        - name: Processing_Pools_Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-processing-pools-database-username
              key: sitecore-processing-pools-database-username
        - name: Processing_Pools_Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-processing-pools-database-password
              key: sitecore-processing-pools-database-password
        - name: Reference_Data_Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-reference-data-database-username
              key: sitecore-reference-data-database-username
        - name: Reference_Data_Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-reference-data-database-password
              key: sitecore-reference-data-database-password    
        - name: Sitecore_License
          valueFrom:
            secretKeyRef:
              name: sitecore-license
              key: sitecore-license
        - name: Sitecore_ConnectionStrings_Messaging
          value: Data Source=$(Database_Server);Initial Catalog=Sitecore.Messaging;User ID=$(Messaging_Database_Username);Password=$(Messaging_Database_Password);
        - name: Sitecore_ConnectionStrings_Xdb.Marketingautomation
          value: Data Source=$(Database_Server);Initial Catalog=Sitecore.Marketingautomation;User ID=$(Marketing_Automation_Database_Username);Password=$(Marketing_Automation_Database_Password);
        - name: Sitecore_ConnectionStrings_Xdb.Processing.Pools
          value: Data Source=$(Database_Server);Initial Catalog=Sitecore.Processing.pools;User ID=$(Processing_Pools_Database_Username);Password=$(Processing_Pools_Database_Password);
        - name: Sitecore_ConnectionStrings_Collection
          value: Data Source=$(Database_Server);Initial Catalog=Sitecore.Xdb.Collection.ShardMapManager;User ID=$(Collection_ShardMapManager_Database_Username);Password=$(Collection_ShardMapManager_Database_Password);
        - name: Sitecore_ConnectionStrings_Xdb.Referencedata
          value: Data Source=$(Database_Server);Initial Catalog=Sitecore.Referencedata;User ID=$(Reference_Data_Database_Username);Password=$(Reference_Data_Database_Password);
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Liveness
          timeoutSeconds: 300
          periodSeconds: 30
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthz/ready
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Startup
          timeoutSeconds: 300
          periodSeconds: 30
          failureThreshold: 10
        volumeMounts:
        - mountPath: C:\inetpub\wwwroot\App_Data\logs
          name: logs
          subPath: xdbcollection
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs  
      imagePullSecrets:
      - name: sitecore-docker-registry