apiVersion: v1
kind: Service
metadata:
  name: xdbsearchworker
spec:
  selector:
    app: xdbsearchworker
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xdbsearchworker
  labels:
    app: xdbsearchworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xdbsearchworker
  template:
    metadata:
      labels:
        app: xdbsearchworker
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-xp1-xdbsearchworker
        image: sitecore-xp1-xdbsearchworker
        env:
        - name: Database_Server
          valueFrom:
            secretKeyRef:
              name: sitecore-databaseservername
              key: sitecore-databaseservername
        - name: Collection_ShardMapManager_Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-collection-shardmapmanager-database-username
              key: sitecore-collection-shardmapmanager-database-username
        - name: Collection_ShardMapManager_Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-collection-shardmapmanager-database-password
              key: sitecore-collection-shardmapmanager-database-password
        - name: Sitecore_License
          valueFrom:
            secretKeyRef:
              name: sitecore-license
              key: sitecore-license
        - name: Sitecore_ConnectionStrings_Collection
          value: Data Source=$(Database_Server);Initial Catalog=Sitecore.Xdb.Collection.ShardMapManager;User ID=$(Collection_ShardMapManager_Database_Username);Password=$(Collection_ShardMapManager_Database_Password);
        - name: Sitecore_ConnectionStrings_SolrCore
          valueFrom:
            secretKeyRef:
              name: sitecore-solr-connection-string-xdb
              key: sitecore-solr-connection-string-xdb
        - name: Sitecore_Sitecore__XConnect__SearchIndexer__Services__Solr.SolrReaderSettings__Options__RequireHttps
          value: 'false'
        - name: Sitecore_Sitecore__XConnect__SearchIndexer__Services__Solr.SolrWriterSettings__Options__RequireHttps
          value: 'false'
        - name: Sitecore_Sitecore__XConnect__CollectionSearch__Services__XConnectSolrHealthCheckServicesConfiguration__Options__RequireHttps
          value: 'false'
        livenessProbe:
          exec:
            command:
            - curl
            - http://localhost:8080/healthz/live          
          timeoutSeconds: 300
          periodSeconds: 30
          failureThreshold: 3
        startupProbe:
          exec:
            command:
            - curl
            - http://localhost:8080/healthz/ready          
          timeoutSeconds: 300
          periodSeconds: 30
          failureThreshold: 10
        volumeMounts:
        - mountPath: C:\service\App_Data\Logs
          name: logs
          subPath: xdbsearchworker
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs
      imagePullSecrets:
      - name: sitecore-docker-registry