- op: add
  path: "/spec/rules/0"
  value:
    host: qa.central.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: hrz
            port: 
              number: 80
- op: add
  path: "/spec/tls/0"
  value:
    secretName: global-hrz-tls
    hosts:
    - qa.central.com