apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: redis
  newName: redis
  newTag: 4.0.14-alpine
- name: solr
  newName: solr
  newTag: 8.8.2

resources:
  - redis.yaml
  - solr.yaml