apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: sitecore-xp1-mssql-init
  newName: sahu123/docker-examples-xp1-mssql-init
  newTag: latest
- name: sitecore-xp1-solr-init
  newName: sahu123/docker-examples-xp1-solr-init
  newTag: latest
resources:
- mssql-init.yaml
- solr-init.yaml
