apiVersion: batch/v1
kind: Job
metadata:
  name: solr-init
spec:
  activeDeadlineSeconds: 900
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      imagePullSecrets:
        - name: sitecore-docker-registry
      containers:
      - name: solr-init
        image: sitecore-xp1-solr-init
        env:
        - name: SITECORE_SOLR_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: sitecore-solr-connection-string
              key: sitecore-solr-connection-string
        - name: SOLR_CORE_PREFIX_NAME
          valueFrom:
            secretKeyRef:
              name: sitecore-solr-core-prefix-name
              key: sitecore-solr-core-prefix-name
      restartPolicy: Never
  backoffLimit: 5
